### ISSUE TITLE
Title: Wordle 

### ISSUE THREAD

**Issue by AyushPathak3011** [Sulagna-Dutta-Roy/Webeginner-projects#10]
### Is your proposal related to a problem? Please describe.

I aim to create a Wordle game based on HTML, CSS, and Javascript.
The user will get 6 chances to guess the word correctly. The word will update after every 24 hours.

As a part of the SSOC '22 program, please assign this issue to me.

**Comment by AyushPathak3011** [comment]
@Sulagna-Dutta-Roy Hey, can you please assign this issue to me, I am a contributor to this project.

**Comment by Shaba1406** [comment]
@Sulagna-Dutta-Roy Please Assign me this issue, i would like to work on this

**Comment by 072arushi** [comment]
@Shaba1406 you have been assigned the issue.
All the best!
