### ISSUE TITLE
Title: email template

### ISSUE THREAD

**Issue by Harsh3363** [Sulagna-Dutta-Roy/Webeginner-projects#103]
### Is your proposal related to a problem? Please describe.

I would like to add a README file to the GitHub repo of the Email template file without this user don't get idea about the website and it's functionality its

### Add any other context or screenshots about the proposal request here.

![emal](https://user-images.githubusercontent.com/72756692/183309172-e720646f-26bd-406a-966e-90559f77ac54.png)

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.
Here are some sample of projects made by me.
https://github.com/Sampurankishoresrivastava

**Comment by Sulagna-Dutta-Roy** [comment]
@Sampurankishoresrivastava kindly add your own Issues. Else don't msg in others section please
