### ISSUE TITLE
Title: CSS Loader

### ISSUE THREAD

**Issue by Vanshiii203** [Sulagna-Dutta-Roy/Webeginner-projects#106]
### Is your proposal related to a problem? Please describe.

Adding more CSS loaders.

**Comment by Sulagna-Dutta-Roy** [comment]
Do you want to add more loaders to the existing project ?

**Comment by Vanshiii203** [comment]
> Do you want to add more loaders to the existing project ?

Yes!

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.
Here are some sample of projects made by me.
https://github.com/Sampurankishoresrivastava/Technovest
https://github.com/Sampurankishoresrivastava/findmatthew_replication
https://github.com/Sampurankishoresrivastava/TinDog-Webpage

**Comment by Sulagna-Dutta-Roy** [comment]
@Sampurankishoresrivastava kindly add your own Issues  I can't assign you here

**Comment by Sulagna-Dutta-Roy** [comment]
what's the updates???

**Comment by Vanshiii203** [comment]
> what's the updates???
I will create a PR today.
