### ISSUE TITLE
Title: Add a random quote generator

### ISSUE THREAD

**Issue by wre9-tesh** [Sulagna-Dutta-Roy/Webeginner-projects#110]
### Is your feature request related to a problem? Please describe.

A quote generator which uses an api to randomly generate a quote from a famous person.

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/96977189/183431993-539b4af4-da5d-4387-99b0-7bbca73cde1f.png)

### Describe alternatives you've considered.

can create it without using api.

**Comment by Sulagna-Dutta-Roy** [comment]
Use Api then it will be a good project.

**Comment by wre9-tesh** [comment]
ok . I will create it using [this](https://github.com/lukePeavey/quotable)  api .please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Go for it
