### ISSUE TITLE
Title:  Sticky Navigation

### ISSUE THREAD

**Issue by Harsh3363** [Sulagna-Dutta-Roy/Webeginner-projects#112]
### Is your proposal related to a problem? Please describe.

The website Sticky navigation needs to change in the UI part like adding a logo to it and also adding icon to it. 

### Add any other context or screenshots about the proposal request here.

![sticky-navigation](https://user-images.githubusercontent.com/72756692/183458450-72d5bd3a-2156-4a0f-8213-eb54632731bc.png)

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.
Here are some sample of nav-bar made by me.
[Files.zip](https://github.com/Sulagna-Dutta-Roy/Webeginner-projects/files/9283473/Files.zip)

**Comment by Sulagna-Dutta-Roy** [comment]
No need to change this I add this as a normal template for beginners. Please open another Issue

**Comment by Harsh3363** [comment]
> No need to change this I add this as a normal template for beginners. Please open another Issue

Sure 👍
