### ISSUE TITLE
Themed Calculator

### ISSUE THREAD

**Issue by Sanskar50** [Sulagna-Dutta-Roy/Webeginner-projects#117]
![Screenshot (70)](https://user-images.githubusercontent.com/99363431/183497190-748abfd0-2315-432a-b984-e807700c91d6.png)
![Screenshot (71)](https://user-images.githubusercontent.com/99363431/183497212-a1b174d1-2a23-476e-a128-f5e69571f8d2.png)
![Screenshot (69)](https://user-images.githubusercontent.com/99363431/183497623-5dc9b6ec-eae2-4e21-93d6-41a8d7723204.png)

NOTE: These are just prototype version images

# THEMED CALCULATOR

- Can perform basic calculations +,-,*,/ on integers and decimal numbers.

- Provides a button to toggle between different themes varying from nature, autumn ,spooky and many more to provide a different experience

# Tech Stack

- HTML, CSS , BOOTSTRAP , JAVASCRIPT

**Comment by Sulagna-Dutta-Roy** [comment]
Already there's one calculator project. Kindly open another Issue.

**Comment by Sanskar50** [comment]
ok @Sulagna-Dutta-Roy
