### ISSUE TITLE
stopwatch 

### ISSUE THREAD

**Issue by srinjoy-26** [Sulagna-Dutta-Roy/Webeginner-projects#12]
### Is your feature request related to a problem? Please describe.

a stopwatch in  python.

### Describe the solution you'd like.

add a project.

### Describe alternatives you've considered.

none.

### Add any other context or screenshots about the feature request here.

![Screenshot 2022-08-06 110027](https://user-images.githubusercontent.com/91176055/183235572-0a7914a8-052d-4811-84e0-0e7e0d3f3f38.png)

**Comment by Sulagna-Dutta-Roy** [comment]
There's already stopwatch project.

**Comment by srinjoy-26** [comment]
> There's already stopwatch project.

ok I'll add in python

**Comment by iamrahul8** [comment]
@Sulagna-Dutta-Roy , Assign this issue to me

**Comment by srinjoy-26** [comment]
> @Sulagna-Dutta-Roy , Assign this issue to me

I have the project ready brother, I will be making a PR

**Comment by iamrahul8** [comment]
> > @Sulagna-Dutta-Roy , Assign this issue to me
> 
> I have the project ready brother, I will be making a PR

😁😁

**Comment by srinjoy-26** [comment]
> > > @Sulagna-Dutta-Roy , Assign this issue to me
> > 
> > 
> > I have the project ready brother, I will be making a PR
> 
> 😁😁

Actually due to exams, I wasn't able to focus on this
