### ISSUE TITLE
Title: Rock, Paper, Scissors Game

### ISSUE THREAD

**Issue by kunalranjan19** [Sulagna-Dutta-Roy/Webeginner-projects#121]
### Is your proposal related to a problem? Please describe.

I want to make Rock, Paper, Scissors Game using HTML, CSS and javascript

**Comment by kunalranjan19** [comment]
Hey, @Sulagna-Dutta-Roy please assign this to me.

**Comment by Sulagna-Dutta-Roy** [comment]
what's the update ??

**Comment by iamrahul8** [comment]
Assign this to me , i have done it already

**Comment by iamrahul8** [comment]
![image](https://user-images.githubusercontent.com/72541381/186483759-c96bec1b-9af0-47fc-bbe3-e2b73104970e.png)

@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy can I work on this issue?

Any update on this @Vanshiii203

**Comment by Vanshiii203** [comment]
> > @Sulagna-Dutta-Roy can I work on this issue?
> 
> Any update on this @Vanshiii203

I'll raise a pr today. Sorry for the delay, I was busy with some CLG stuff
