### ISSUE TITLE
Title: Donation Website

### ISSUE THREAD

**Issue by Mahak008** [Sulagna-Dutta-Roy/Webeginner-projects#124]
### Is your proposal related to a problem? Please describe.

This is a responsive website where people can donate money and also become a member of it. This website is made purely using HTML, CSS and Bootstrap and CSS Animations. I have used Razorpay for the payment gateway integration.

Kindly assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
What's the update ???

**Comment by Mahak008** [comment]
Hey Sulagna!
I will submit the code by tonight or tomorrow. I am facing some issue in its execution. I am really very sorry for the delay.
