### ISSUE TITLE
Title:  Dice game

### ISSUE THREAD

**Issue by Harsh3363** [Sulagna-Dutta-Roy/Webeginner-projects#129]
### Is your proposal related to a problem? Please describe.

In the dice game in the footer section, the company name can be removed and also functionality to add the name in place of dice 1 and dice 2 can be added ,

### Add any other context or screenshots about the proposal request here.

![dice-game](https://user-images.githubusercontent.com/72756692/184236698-14c90534-9c46-41fb-99db-1cba95334894.png)

**Comment by Sulagna-Dutta-Roy** [comment]
This Issue is already here

**Comment by Harsh3363** [comment]
Okay
