### ISSUE TITLE
Text to speech converter in javascript.

### ISSUE THREAD

**Issue by srinjoy-26** [Sulagna-Dutta-Roy/Webeginner-projects#13]
### Is your feature request related to a problem? Please describe.

add a Text to speech converter in html , css and javascript.

### Describe the solution you'd like.

This project converts given text to speech in desired language.

### Describe alternatives you've considered.

none.

### Add any other context or screenshots about the feature request here.

https://user-images.githubusercontent.com/91176055/182888131-50180128-6f9a-4859-b677-c8317b82e6d3.mp4

**Comment by mdnazisharman2803** [comment]
@Sulagna-Dutta-Roy  this is intermediate level.. Please change label.. And give me the access to this repository so i don't have to mention you always to fix..
