### ISSUE TITLE
word to pdf converter  

### ISSUE THREAD

**Issue by srinjoy-26** [Sulagna-Dutta-Roy/Webeginner-projects#142]
### Is your feature request related to a problem? Please describe.

no , word to pdf converter  in python.

### Describe the solution you'd like.

add the project

### Describe alternatives you've considered.

none

### Add any other context or screenshots about the feature request here.

https://user-images.githubusercontent.com/91176055/184478793-92f201e2-6e6d-423c-a81b-614ec56526c3.mp4

**Comment by Sulagna-Dutta-Roy** [comment]
please complete it. What's the update ?

**Comment by srinjoy-26** [comment]
> please complete it. What's the update ?

Today I'll make a pr
