### ISSUE TITLE
Facebook Login Page Clone Build 

### ISSUE THREAD

**Issue by Rancho2002** [Sulagna-Dutta-Roy/Webeginner-projects#145]
Tailwind CSS is an amazing framework for upcoming technology. This project is created with tailwind css, and then build using npm build. It is an example for beginners who want to clone already built websites for practice.
![cloneLogin](https://user-images.githubusercontent.com/92109154/184499647-11cf0145-b497-4fb2-b21a-76dc20acb0cb.png)
[SSOC]

**Comment by Sulagna-Dutta-Roy** [comment]
You will use html,css ?? Please don't add react project here

**Comment by Rancho2002** [comment]
yes, only HTML, CSS

**Comment by Rancho2002** [comment]
Hi @Sulagna-Dutta-Roy pls tell if I created a valid issue or not? If yes, then pls assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
I will assign you by tomorrow, don't worry. Also sorry for the delay
