### ISSUE TITLE
Title:  Addition of an TO-DO Web-application [SSOC]

### ISSUE THREAD

**Issue by ravish036** [Sulagna-Dutta-Roy/Webeginner-projects#159]
### Is your proposal related to a problem? Please describe.

- An To-Do list generator helps you to record all your tasks at one place.
- Features : It contain mainly 2 sections ,
1. Todos : In this section you can enter your to do tasks/works .
2. Already done : This section contains all the finished task which were previously present in TODOS section.

- Tech stack used : HTML5, CSS3, JAVASCRIPT .  

### Add any other context or screenshots about the proposal request here.

![image](https://user-images.githubusercontent.com/84343005/184732629-447493d1-683c-43ff-ba59-cf6aaa1a5c89.png)

![image](https://user-images.githubusercontent.com/84343005/184732701-9c0f88cd-ef7f-49d7-972b-12a404e3f5f7.png)

**Comment by Pransav290302** [comment]
i would like to work on this to-do list @ravish036 can please assign me ?

**Comment by Sulagna-Dutta-Roy** [comment]
> ### Is your proposal related to a problem? Please describe.
> 
> - An To-Do list generator helps you to record all your tasks at one place.
> - Features : It contain mainly 2 sections ,
> 1. Todos : In this section you can enter your to do tasks/works .
> 2. Already done : This section contains all the finished task which were previously present in TODOS section.
> 
> - Tech stack used : HTML5, CSS3, JAVASCRIPT .  
> 
> ### Add any other context or screenshots about the proposal request here.
> 
> ![image](https://user-images.githubusercontent.com/84343005/184732629-447493d1-683c-43ff-ba59-cf6aaa1a5c89.png)
> 
> ![image](https://user-images.githubusercontent.com/84343005/184732701-9c0f88cd-ef7f-49d7-972b-12a404e3f5f7.png)
> 

Already this project here. Kindly open new Issue
