### ISSUE TITLE
Title: Keeper App

### ISSUE THREAD

**Issue by vaibhavchaubey** [Sulagna-Dutta-Roy/Webeginner-projects#16]
### Is your feature request related to a problem? Please describe.

I would like to work on the HTML, CSS, ReactJs, and Javascript-based Keeper App. It is similar to Google Keep. It allows users to add their Notes. In this Keeper project, users can add and delete their Notes. 

As soon as you assign me the issue, I can get to work.
Waiting for your response 😊

### Describe the solution you'd like.

A Keeper App which is used to add notes

### Describe alternatives you've considered.

none

**Comment by Sulagna-Dutta-Roy** [comment]
Just a query can you please tell me is it a reactjs project or not???

**Comment by vaibhavchaubey** [comment]
> Just a query can you please tell me is it a reactjs project or not???

Yes, it is a reactjs project.
It would be great if you can assign me this project

**Comment by Sulagna-Dutta-Roy** [comment]
Actually currently I'm accepting only Js based projects. So it would be great

**Comment by vaibhavchaubey** [comment]
> Actually currently I'm accepting only Js based projects. So it would be great 

So i can work on this project or not?

**Comment by vaibhavchaubey** [comment]
> Sorry to say this Reactjs project because of repository configurations. Kindly consider this for the next time. But you can add any JavaScript projects here without any library framework

No problem
Just a reminder I have made issues for Todo_list and Dice-Game.
It would be great if you check them out and assign them to me so I can work on them.

**Comment by Sulagna-Dutta-Roy** [comment]
I will assign you after get any guidelines from ssoc 😄

**Comment by vaibhavchaubey** [comment]
> I will assign you after get any guidelines from ssoc 😄

Thanks 😃
