### ISSUE TITLE
Title:  Password Generator

### ISSUE THREAD

**Issue by hady68** [Sulagna-Dutta-Roy/Webeginner-projects#169]
### Is your feature request related to a problem? Please describe.

This project is a **Password generator** that will be made using HTML, CSS, and Javascript.

### Describe the solution you'd like.

-  A password generator app to generate passwords 
- User enters the password length -> the password is generated
 
Other features ->

1.  Checkbox to contain Uppercase to generate a password using that 
2. Checkbox to contain Lowercase to generate a password using that 
3. Checkbox to contain Numbers to generate a password using that 
4. Checkbox to contain Symbols to generate a password using that 

Tech stack used : HTML5, CSS3, JAVASCRIPT .

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I will be making something similar to this :
![image](https://user-images.githubusercontent.com/64458111/185032404-5f911f20-c8a8-4944-9fb3-c8bd8a73c32e.png)

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already exist. Kindly open another Issue

**Comment by hady68** [comment]
> This project is already exist. Kindly open another Issue

Alright
