### ISSUE TITLE
Title:Currency convertor

### ISSUE THREAD

**Issue by Vanshiii203** [Sulagna-Dutta-Roy/Webeginner-projects#173]
### Is your proposal related to a problem? Please describe.

I would like to enhance the UI of currency convertor.

**Comment by Shaba1406** [comment]
hey @Sulagna-Dutta-Roy , I Would like to Work on this issue by enhancing the UI of currency convertor

**Comment by Sulagna-Dutta-Roy** [comment]
@Vanshiii203 please attach any picture for the UI

**Comment by Shaba1406** [comment]
@Sulagna-Dutta-Roy / I want to Work on this issue in improving it's UI Please assign this to me 
![Currency convertor - Google Chrome 31-08-2022 16_42_35](https://user-images.githubusercontent.com/97939567/187666277-931dcd1c-57ea-4cfe-b7bd-68235e0b3f53.png)

**Comment by Vanshiii203** [comment]
@Sulagna-Dutta-Roy 

this is the current background of the convertor.
![Screenshot (364)](https://user-images.githubusercontent.com/94471189/187671675-ee1c2394-5ae6-43c5-81dd-0e1c41a4cbd9.png)

https://user-images.githubusercontent.com/94471189/187672438-782d78ca-f348-45a4-a7ee-13a3767c1b81.mp4

I would like to change the background  and also improve the hover effect and add transition of the button.
