### ISSUE TITLE
Title: PG Life

### ISSUE THREAD

**Issue by Mahak008** [Sulagna-Dutta-Roy/Webeginner-projects#187]
### Is your proposal related to a problem? Please describe.

It is a website where you can search for PG's at your desired location. It is created using HTML, CSS, Bootstrap and Javascript.
Kindly assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Will you going to use any API for this ???

**Comment by Mahak008** [comment]
> Will you going to use any API for this ???

No, as of now I won't be using any api
