### ISSUE TITLE
Title:  Text-Formatter 

### ISSUE THREAD

**Issue by Abbhiishek** [Sulagna-Dutta-Roy/Webeginner-projects#2]
### Is your proposal related to a problem? Please describe.

Hey Sulagna, 
I would love to work on the text-formatter app where users can give any text and through buttons and scale input, they can change the property of the text easily.
For now, I am aiming to include color, size, and decoration properties.

I can start working from the day you assign the issue to me.

Kudos 🙌 !

**Comment by Sulagna-Dutta-Roy** [comment]
Wait till 1st August for Inauguration of SSOC'22. We Project Admins doesn't have any guidelines yet. Then I will surely assign to you. Happy to connect ❤️
