### ISSUE TITLE
Title: Dice-Game

### ISSUE THREAD

**Issue by vaibhavchaubey** [Sulagna-Dutta-Roy/Webeginner-projects#21]
### Is your feature request related to a problem? Please describe.

Hello @Sulagna-Dutta-Roy,
I would like to work on a Javascript-based Dice-Game project.
Please assign this to me.
Waiting for your response

### Describe the solution you'd like.

I want to add this project.

### Describe alternatives you've considered.

none

**Comment by Anshitseth** [comment]
I want to work on Dice-game project .
please assign it to me @sulagna-Dutta-Roy maam.

**Comment by vaibhavchaubey** [comment]
> I want to work on Dice-game project .
> please assign it to me @sulagna-Dutta-Roy maam.
>   

Sorry but i have already selected this Dice-Game project. So please create another issue

**Comment by Sulagna-Dutta-Roy** [comment]
Actually Issues will serve on first serve basis. If someone opens Issue first then he'll be assigned. Otherwise if he/she unable to do it will assign the another person.

**Comment by vaibhavchaubey** [comment]
> Actually Issues will serve on first serve basis. If someone opens Issue first then he'll be assigned. Otherwise if he/she unable to do it will assign the another person.
Can you please assign me the issue

**Comment by vaibhavchaubey** [comment]
@Sulagna-Dutta-Roy please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
We admins doesn't have any guidelines now. Once we get then assign you
