### ISSUE TITLE
Add a todo list website

### ISSUE THREAD

**Issue by wre9-tesh** [Sulagna-Dutta-Roy/Webeginner-projects#217]
### Is your feature request related to a problem? Please describe.

I want to add a todo list app .The app will have dark and light mode , user can sort their task in states like completed , active, and  can also delete completed tasks.

## ScreenShot
![image](https://user-images.githubusercontent.com/96977189/186196165-0be238a2-dc83-494f-b19f-b9adcc5a60c4.png)

### Describe the solution you'd like.

The app will be built using Html , css and Vanilla Javascript.

### Describe alternatives you've considered.

it can also show no of remaining tasks and will be responsive

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already exist in the repository.kindly open another Issue
