### ISSUE TITLE
Title: A Decentralized food delivery app built using React Js , Solidity and ethers.js

### ISSUE THREAD

**Issue by Adithya-Sr** [Sulagna-Dutta-Roy/Webeginner-projects#234]
### Is your proposal related to a problem? Please describe.

 Its a decentralized app (Dapp) for food delivery  which will accept payment in cryptocurrency and  authenticate the user using his Crypto Wallet (like Metamask ) .

Since it uses  a Decentralized wallet to authenticate a user ,it won't collect and store his Email ID and Phone No.

### Add any other context or screenshots about the proposal request here.

No response

**Comment by Sulagna-Dutta-Roy** [comment]
Currently reactjs projects not accepting.

**Comment by Adithya-Sr** [comment]
No problem 👍
