### ISSUE TITLE
Title: Search Bar

### ISSUE THREAD

**Issue by Shaba1406** [Sulagna-Dutta-Roy/Webeginner-projects#269]
### Is your proposal related to a problem? Please describe.

I would like to create a Search Bar.
 
![Search Bar - Google Chrome 11-09-2022 21_15_55](https://user-images.githubusercontent.com/97939567/189536904-c738c23c-97f3-4242-addc-5665abde0019.png)

**Comment by Shaba1406** [comment]
Please Assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Add more features to it. This is so simple

**Comment by Shaba1406** [comment]
@Sulagna-Dutta-Roy Can i replace it with the google clone
