### ISSUE TITLE
Title: CheatSheet Template

### ISSUE THREAD

**Issue by rtewari056** [Sulagna-Dutta-Roy/Webeginner-projects#279]
### Is your feature request related to a problem? Please describe.

This is a  CheatSheet template. I have created this template to boost my project workflow by copying long code snippets and will be helpful for others as well.

### Describe the solution you'd like.

The code is written in HTML, CSS and JavaScript only.

### Describe alternatives you've considered.

A good alternative for copy/paste frequently used code snippets without doing multiple google search.

### Add any other context or screenshots about the feature request here.

![Cheatsheet](https://user-images.githubusercontent.com/75976169/190885743-6b38553f-3871-4cd7-8357-3daa0900c151.png)

**Comment by rtewari056** [comment]
@Sulagna-Dutta-Roy Kindly assign this issue to me

**Comment by Sulagna-Dutta-Roy** [comment]
It could be a documentation I think. This is not a particular project

**Comment by rtewari056** [comment]
Its a project in which you can add your own code snippets for reference and host the web page to access from anywhere

**Comment by rtewari056** [comment]
@Sulagna-Dutta-Roy kindly assign me this issue
