### ISSUE TITLE
Title: Recipe App

### ISSUE THREAD

**Issue by Shaba1406** [Sulagna-Dutta-Roy/Webeginner-projects#286]
### Is your proposal related to a problem? Please describe.

I want to Create A Recipe App where you can search and get the recipe of Dishes.

### Add any other context or screenshots about the proposal request here.

![REcipe ](https://user-images.githubusercontent.com/97939567/191279418-8acb098b-3668-4c1c-8d80-14d2634eeb41.png)

**Comment by Shaba1406** [comment]
I know a Random recipe Generator is also present but my proposal includes search option as well

**Comment by Shaba1406** [comment]
Please assign me this @Sulagna-Dutta-Roy

**Comment by 072arushi** [comment]
@Shaba1406 you are being assigned this issue. All the best!!
