### ISSUE TITLE
Title: Exploratory data  analysis using student dataset

### ISSUE THREAD

**Issue by Labheshm11** [Sulagna-Dutta-Roy/Webeginner-projects#288]
### Is your proposal related to a problem? Please describe.

1. We will be analyzing the student dataset from Kaggle
2. We will explore the marks of the students from the different subject points of view
3. We will classify them based on various types of graphs

**Comment by Labheshm11** [comment]
@072arushi 
@Sulagna-Dutta-Roy 
Plz assign me the issue

**Comment by 072arushi** [comment]
@Labheshm11 you are being assigned this issue. All the best!
