### ISSUE TITLE
Title: BMI calculator

### ISSUE THREAD

**Issue by kunalranjan19** [Sulagna-Dutta-Roy/Webeginner-projects#291]
### Is your feature request related to a problem? Please describe.

yes it is ,It is a simple BMI calculator made using HTML CSS and javascript

### Describe the solution you'd like.

It is a simple BMI calculator made using HTML CSS and javascript

### Describe alternatives you've considered.

nope

### Add any other context or screenshots about the feature request here.

![WhatsApp Image 2022-09-22 at 15 31 58](https://user-images.githubusercontent.com/93333582/191718770-2b92d121-67ce-48ac-9833-0014d933740c.jpeg)

**Comment by kunalranjan19** [comment]
hey @Sulagna-Dutta-Roy please assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already exist on my repository.kindly open new Issue

**Comment by kunalranjan19** [comment]
okay!!!
