### ISSUE TITLE
Title : Online-Notepad

### ISSUE THREAD

**Issue by iamrahul8** [Sulagna-Dutta-Roy/Webeginner-projects#3]
### Is your proposal related to a problem? Please describe.

Hello Ma'am,
I would like working on the HTML, CSS, and Javascript-based Online Notepad programme, which allows users to use a simple real-time notepad.
As soon as you provide me the issue, I can get to work.
Waiting for your response 😊🚀

### Add any other context or screenshots about the proposal request here.

Request to submit project under SSOC'22.

**Comment by Sulagna-Dutta-Roy** [comment]
Wait till 1st August for Inauguration of SSOC'22. We Project Admins doesn't have any guidelines yet. Then I will surely assign to you. Happy to connect ❤️
