### ISSUE TITLE
Title: Word count

### ISSUE THREAD

**Issue by kunalranjan19** [Sulagna-Dutta-Roy/Webeginner-projects#303]
### Is your feature request related to a problem? Please describe.

yes it helps you to calculate the length of the word.

### Describe the solution you'd like.

It is made with HTMl ,CSS and javascript

### Describe alternatives you've considered.

nothing

### Add any other context or screenshots about the feature request here.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/93333582/192086239-24eead79-949e-4767-a4f3-69c3a76f166f.png">

**Comment by kunalranjan19** [comment]
hey @Sulagna-Dutta-Roy please assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
this project is already exist. check it out #258
