### ISSUE TITLE
Meme Generator with javaScript

### ISSUE THREAD

**Issue by Rishikavishnoi** [Sulagna-Dutta-Roy/Webeginner-projects#308]
### Is your proposal related to a problem? Please describe.

Build a meme generator web app using Html, CSS, and javascript. In which we can upload images and write text on it.

**Comment by Sulagna-Dutta-Roy** [comment]
Use Javascript meme api for the project.

**Comment by Rishikavishnoi** [comment]
@Sulagna-Dutta-Roy okay
