### ISSUE TITLE
Title: Digital clock

### ISSUE THREAD

**Issue by kunalranjan19** [Sulagna-Dutta-Roy/Webeginner-projects#312]
### Is your feature request related to a problem? Please describe.

yes!! the last issue that i created with the same name got merged into the forked repo and the issue got closed 

### Describe the solution you'd like.

made with HTML CSS and js

### Describe alternatives you've considered.

no

### Add any other context or screenshots about the feature request here.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/93333582/192149795-6459091c-f456-4b72-9d7c-9e501bb10723.png">

**Comment by kunalranjan19** [comment]
hey @Sulagna-Dutta-Roy please assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already done by you. So same project not accepted #11
