### ISSUE TITLE
Title: note

### ISSUE THREAD

**Issue by kunalranjan19** [Sulagna-Dutta-Roy/Webeginner-projects#314]
### Is your feature request related to a problem? Please describe.

it is a note taking web page

### Describe the solution you'd like.

made using HTML CSS and js

### Describe alternatives you've considered.

none

### Add any other context or screenshots about the feature request here.

![Uploading image.png…]()

**Comment by kunalranjan19** [comment]
hey @Sulagna-Dutta-Roy please assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
#3 this project is already existed.
