### ISSUE TITLE
Currently the website is not redirecting to any projects. I can see there's no link attached to the projects image. Does it suppose to be like this? 

### ISSUE THREAD

**Issue by SK-21** [Sulagna-Dutta-Roy/Webeginner-projects#333]
## There's no link attached to the project image.

- So after visiting the homepage user won't be able to check the projects. 
- This will not create a good user experience.
- Also we can add the project name with the image as well for UI.

### Describe the solution you'd like.

- [ ] We can add the respective links of the project with the image
- [ ] We can add the project name with the project image for better readability.
- [ ] We can add all the projects on the homepage itself.

## I can resolve all the issues and add also new layout to make the UI better.

- I CAN SEE THERE'S A NEED TO CHANGE THE UI A BIT FOR CREATING BETTER USER EXPERENCE.

**Comment by Sulagna-Dutta-Roy** [comment]
It's a sample website provided. You can work on it if you want to

**Comment by SK-21** [comment]
thank Sulagna
