### ISSUE TITLE
Email validator website

### ISSUE THREAD

**Issue by Anshu3301** [Sulagna-Dutta-Roy/Webeginner-projects#336]
### Is your feature request related to a problem? Please describe.

There are many projects but I think there's this mini project that can be helpful for beginners.

### Describe the solution you'd like.

Adding a new project of Email Validator using OTP

### Describe alternatives you've considered.

Check out the preview video of my project here. If you like it then I'll raise a PR.

### Add any other context or screenshots about the feature request here.

Preview:
![Screenshot (171)](https://github.com/Sulagna-Dutta-Roy/Webeginner-projects/assets/134282893/42e1a651-0912-4dc0-aaf4-53f53a21b7a5)

![Screenshot (172)](https://github.com/Sulagna-Dutta-Roy/Webeginner-projects/assets/134282893/f959d6be-a576-4048-b46b-21cccc14b071)

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Anshu3301 wanted to know if you're from girlscript summer of code?

**Comment by Anshu3301** [comment]
Yes, I am.

**Comment by Sulagna-Dutta-Roy** [comment]
But this project isn't accepted in the gssoc program.

**Comment by Tanishka023** [comment]
Hey!! I am excited to contribute to this project, please assign this to me @Sulagna-Dutta-Roy

**Comment by Tanishka023** [comment]
> Hey!! I am excited to contribute to this project, please assign this to me @Sulagna-Dutta-Roy 

Thanks @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Tanishka023 before raising this Issues. Did you check it's mentioned about SSOC'22 tags in my repository. 
Also let me know how everyone raising this issues here?

**Comment by Tanishka023** [comment]
> Hello @Tanishka023 before raising this Issues. Did you check it's mentioned about SSOC'22 tags in my repository. 
> Also let me know how everyone raising this issues here? 

Why has this issue been closed? @Sulagna-Dutta-Roy
