### ISSUE TITLE
Text Editor Using Python

### ISSUE THREAD

**Issue by Avik-creator** [Sulagna-Dutta-Roy/Webeginner-projects#35]
### Is your proposal related to a problem? Please describe.

It will be made using Python.

**Comment by Avik-creator** [comment]
@Sulagna-Dutta-Roy please assign me this

**Comment by siddhi-244** [comment]
> ### Is your proposal related to a problem? Please describe.
> It will be made using Python.
> 
> ### Add any other context or screenshots about the proposal request here.
> _No response_

Go for it🥳
