### ISSUE TITLE
Title: SlideShare to PDF

### ISSUE THREAD

**Issue by Avik-creator** [Sulagna-Dutta-Roy/Webeginner-projects#38]
### Is your proposal related to a problem? Please describe.

We have to sign up to Scribd for seeing presentation. With this script we would be able to download the pdf version of it.

**Comment by Avik-creator** [comment]
@Sulagna-Dutta-Roy please assign me this

**Comment by siddhi-244** [comment]
Which techstack you are gonna use for this project?

**Comment by Avik-creator** [comment]
Python I should say

**Comment by siddhi-244** [comment]
Looks good then !
