### ISSUE TITLE
Title:  Weather app for non-google services phone

### ISSUE THREAD

**Issue by biratdatta** [Sulagna-Dutta-Roy/Webeginner-projects#4]
### Is your feature request related to a problem? Please describe.

There is always a problem for Huawei users to search weather on the go due to lack of Google Services. I would like to make a simple react app for the people who are using Huawei based phones to see weather and all.

### Describe the solution you'd like.

The solution is pretty simple. I will fetch an api for the weather and make a frontend for it to integrate with.

 

### Describe alternatives you've considered.

I am thinking to make another go to simple to-do list app for the said Non- Google Services app

### Add any other context or screenshots about the feature request here.

![Uploading image.png…]()

**Comment by Sulagna-Dutta-Roy** [comment]
Wait till 1st August for Inauguration of SSOC'22. We Project Admins doesn't have any guidelines yet. Then I will surely assign to you. Happy to connect ❤️
