### ISSUE TITLE
Title: React Application for managing personal notes on the cloud

### ISSUE THREAD

**Issue by rtewari056** [Sulagna-Dutta-Roy/Webeginner-projects#40]
### Is your proposal related to a problem? Please describe.

Hey @Sulagna-Dutta-Roy
I would like to work on a React App which can be used to manage personal notes. So, your question would be what's new in it?
My answer is that the application will be cloud based with user authentication. Along with that I am going to use password hashing for securely store passwords on the database. 
Waiting for your response 🙂

**Comment by siddhi-244** [comment]
This repository currently focuses on javascript and python based projects.

**Comment by rtewari056** [comment]
> This repository currently focuses on javascript and python based projects.

Should I make another issue for JS and Python based project?

**Comment by siddhi-244** [comment]
Sure
