### ISSUE TITLE
Title: A common webage to view all the projects

### ISSUE THREAD

**Issue by SSHSRN** [Sulagna-Dutta-Roy/Webeginner-projects#41]
### Is your feature request related to a problem? Please describe.

There will be many projects done, but a user seeing the repository for the first time might be confused seeing the repository file structure. So, I will add a deployable webpage that will showcase all the projects in the repository so that it is easy for newcomers to check the projects and also for the SSOC participants to check if their project idea is already taken by somebody else.

### Describe the solution you'd like.

Adding a html file at the repository parent folder and deploying it.

### Describe alternatives you've considered.

There are no other alternatives to consider. I will add a common **index.html** file in the **repository parent folder** linking all the projects created. I will also periodically update it so that it's always up to date.

**Comment by Sulagna-Dutta-Roy** [comment]
It's been 14days ?? what's the update ?

**Comment by SSHSRN** [comment]
I did mention that I was out of town and I needed some more time (in Discord). Actually I am working on a hackathon right now. I will definitely post an update by tomorrow.

And a doubt.. Should I solve an issue with a single commit? or can I do one very basic commit and keep updating/upgrading it?
Kindly confirm...

**Comment by Sulagna-Dutta-Roy** [comment]
Actually I need to update all of the scores and report to the PM. This is why I'm asking here. Actually it's a long gap and people are asking me to assign those Issues with no update.
