### ISSUE TITLE
Title: Add Rock-Paper-Scissor Game(User vs. Computer) using Python

### ISSUE THREAD

**Issue by SSHSRN** [Sulagna-Dutta-Roy/Webeginner-projects#42]
### Is your feature request related to a problem? Please describe.

This project will show how to implement a game named Rock-Paper-Scissor with just the basics of python.

### Describe alternatives you've considered.

I considered other programming languages can be used, but python is the easiest language to code.

**Comment by siddhi-244** [comment]
Add one game per pr ! That would be easy to review. If it's okayy I can assign this issue to you !

**Comment by akanksha0812** [comment]
Please assign this to me

**Comment by SSHSRN** [comment]
@siddhi-244 Actually these three games are really simple and are very basic ones. (Even after combining all 3 and with comments, it only came up to 130 loc...)That's why added them together. Can you please assign them to me?

**Comment by Sulagna-Dutta-Roy** [comment]
@SSHSRN But this is not acceptable you need to create 3Issues and PRs. Whatever it's basic or advanced level doesn't matter. You can check other projects here.

**Comment by SSHSRN** [comment]
Okk. I got it @Sulagna-Dutta-Roy . I'll edit this issue and add a new issue for each game. But I got 2 doubts now.
1. I understood how to edit an issue, but can I also edit a PR? Like add a new commit and modify the PR? Please guide me in doing so...
2. Should I again add a new folder, main.py and Readme files for each game or can I just group them all in same folder and just create separate issues and PRs?

Kindly confirm!

**Comment by siddhi-244** [comment]
Sure
