### ISSUE TITLE
Title: Youtube Dashboard Clone

### ISSUE THREAD

**Issue by harshit-paneri** [Sulagna-Dutta-Roy/Webeginner-projects#44]
### Is your proposal related to a problem? Please describe.

To learn How to clone any website.

**Comment by harshit-paneri** [comment]
@siddhi-244 Please assign me

**Comment by siddhi-244** [comment]
Will you be making it using html css and js?

**Comment by harshit-paneri** [comment]
Yes

**Comment by siddhi-244** [comment]
> Yes

Go for it🥳🥳

**Comment by harshit-paneri** [comment]
Hey 👋🏻 @siddhi-244 Is it any deadline of any Issue

**Comment by siddhi-244** [comment]
> Hey 👋🏻 @siddhi-244 Is it any deadline of any Issue
 Let me talk to the admin. But try to resolve the issues asap !
