### ISSUE TITLE
Title: dice roll game 

### ISSUE THREAD

**Issue by leesha19** [Sulagna-Dutta-Roy/Webeginner-projects#45]
### Is your feature request related to a problem? Please describe.

the game will create some random number on dice will decide the player who wins

### Describe the solution you'd like.

I want to create a dice roll game 

### Describe alternatives you've considered.

its a game

**Comment by akanksha0812** [comment]
Hey , 
I want to contribute in this project,
Please assign this to me!

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already in the repository.
