### ISSUE TITLE
Title: home page 

### ISSUE THREAD

**Issue by leesha19** [Sulagna-Dutta-Roy/Webeginner-projects#46]
### Is your feature request related to a problem? Please describe.

there is no home page 

### Describe the solution you'd like.

I will create a home page

### Describe alternatives you've considered.

the home page will contain all the projects

**Comment by akanksha0812** [comment]
Please assign this to me I will add all the necessary sections , including home page containing navbar , projects details and some other features.

**Comment by akanksha0812** [comment]
![home ss for ssoc](https://user-images.githubusercontent.com/90760374/183391967-9ab151b0-e56d-4b37-9f1a-0eb8e3cfaf96.png)
 this is just for demo i will organize things and make different sections.

**Comment by akanksha0812** [comment]
this is just for demo , I will add all features
![new home ssoc](https://user-images.githubusercontent.com/90760374/183393064-74adcfbc-9f4d-485b-8a2d-7dbc770fabf6.png)

**Comment by leesha19** [comment]
I am already working on it ..this issue is assigned to me
