### ISSUE TITLE
Title: Two step Form 

### ISSUE THREAD

**Issue by iamrahul8** [Sulagna-Dutta-Roy/Webeginner-projects#49]
### Is your proposal related to a problem? Please describe.

- Two step form with validation (mob no., email etc.)
- Rsponsive design

### Add any other context or screenshots about the proposal request here.

Submission under SSOC 22

**Comment by iamrahul8** [comment]
Just like google forms; user can't move further before filling required section.

**Comment by priyanshi1282** [comment]
@iamrahul8 hey please provide the screen shots of your project.

**Comment by iamrahul8** [comment]
![image](https://user-images.githubusercontent.com/72541381/183259244-f171b2d3-19e9-4cd4-9e28-a929aa58f750.png)

**Comment by imaaquibali** [comment]
@iamrahul8 go for it try to make it attractive.
