### ISSUE TITLE
Title: Weather WebApp

### ISSUE THREAD

**Issue by Rishikavishnoi** [Sulagna-Dutta-Roy/Webeginner-projects#51]
### Is your proposal related to a problem? Please describe.

Build a weather app using HTML CSS & JavaScript.

**Comment by mdnazisharman2803** [comment]
@siddhi-244  kindly assign this to @Rishikavishnoi

**Comment by siddhi-244** [comment]
> ### Is your proposal related to a problem? Please describe.
> Build a weather app using HTML CSS & JavaScript.
> 
> ### Add any other context or screenshots about the proposal request here.
> _No response_

Go for it🥳🥳
