### ISSUE TITLE
Title: Adding Javascript Calculator

### ISSUE THREAD

**Issue by Rishikavishnoi** [Sulagna-Dutta-Roy/Webeginner-projects#53]
### Is your proposal related to a problem? Please describe.

Its a calculator project build using HTML,CSS , and javascript.

**Comment by mdnazisharman2803** [comment]
There are 3 issues already opened as calculator, check and tell if you're going to make the same or different?

**Comment by Rishikavishnoi** [comment]
@mdnazisharman2803  okay

**Comment by Sulagna-Dutta-Roy** [comment]
Sorry, already calculator project here. So I need to close this Issue
