### ISSUE TITLE
Title: Stopwatch 

### ISSUE THREAD

**Issue by Harsh3363** [Sulagna-Dutta-Roy/Webeginner-projects#57]
### Is your proposal related to a problem? Please describe.

The Stopwatch web app interface can be improved
Like the whole part could be made in the middle of the screen and many other changes could be done for better interface.

![stop-watch](https://user-images.githubusercontent.com/72756692/183138231-e4caf12a-b16a-42f5-99e8-4044f77dcfee.png)

**Comment by Harsh3363** [comment]
Hii @Sulagna-Dutta-Roy  please assign this to me I would like to make the UI more interactive

**Comment by MDeexith** [comment]
@Sulagna-Dutta-Roy please assign this to me and I already made changes and added new features. please accept my pull request on same. Thank You
