### ISSUE TITLE
Title: Tic Tac Toe Game using HTML, CSS, JS

### ISSUE THREAD

**Issue by sudarsan2k5** [Sulagna-Dutta-Roy/Webeginner-projects#63]
### Is your proposal related to a problem? Please describe.

Building a Tic Tac Toe Game using HTML, CSS, JS.

**Comment by sudarsan2k5** [comment]
Hi @Sulagna-Dutta-Roy please assign this to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Hey,what's the update ??

**Comment by lucifer694u** [comment]
hey i would l am newbie and interseted in contributing  in this issue
