### ISSUE TITLE
Title: simon game

### ISSUE THREAD

**Issue by Harsh3363** [Sulagna-Dutta-Roy/Webeginner-projects#7]
### Is your proposal related to a problem? Please describe.

Hello @Sulagna-Dutta-Roy,
I would like to work on a Javascript-based Simon game project.
Please assign this to me.
Waiting for your response

**Comment by Sulagna-Dutta-Roy** [comment]
Wait until 1st August Inauguration. Then I will assign to you. Thank you

**Comment by Harsh3363** [comment]
> Wait until 1st August Inauguration. Then I will assign to you. Thank you 

Thanks for your reply
Also the 'me' link of ping me on your README is not redirecting to your LinkedIn.

**Comment by Sulagna-Dutta-Roy** [comment]
Oh okay , I will check it sure
