### ISSUE TITLE
Title:  Youtube Video Downloader In Python

### ISSUE THREAD

**Issue by Abbhiishek** [Sulagna-Dutta-Roy/Webeginner-projects#77]
### Is your proposal related to a problem? Please describe.

Hey, 

Can i contribute to the repository with a python project where we can easily download any video from youtube within a few keyboard strokes?

Features of the application :
1. Can download videos in different quality and aspect ratios.
2. There would also be an option to download audio only for podcasts.

Kindly assign this issue to me 🤩

**Comment by Sulagna-Dutta-Roy** [comment]
Sorry this Issue already here.
