### ISSUE TITLE
Sorting visualizer

### ISSUE THREAD

**Issue by kshitijmishra27** [Sulagna-Dutta-Roy/Webeginner-projects#8]
### Is your feature request related to a problem? Please describe.

Hello Ma'am,
I would like to work on the HTML, CSS, and Javascript-based Sorting Visualizer, which allows users to  
Visualize and learn the algorithms this will help out users to learn DSA efficiently

As soon as you provide me the issue, I can get to work.
Waiting for your response 😊🚀

### Describe the solution you'd like.

The solution is pretty simple.  I will add  algorithms like merge sort, quick sort, bubble sort, insertion sort etc

### Describe alternatives you've considered.

 i will add key features like Controlling the speed of the algo and adding no. of items in the Array

**Comment by kshitijmishra27** [comment]
hey @Sulagna-Dutta-Roy 
when will you assign me? i choose this project :)

**Comment by Sulagna-Dutta-Roy** [comment]
I will assign you after getting any guidelines from ssoc. Wait until 3rd August , Thank you 😄

**Comment by Sulagna-Dutta-Roy** [comment]
16 days ago I assigned but no PR for here. What's the update ?? Otherwise I will assign to another

**Comment by kshitijmishra27** [comment]
yes i am gonna finish it shortly 😄
