### ISSUE TITLE
Title: Todo-List

### ISSUE THREAD

**Issue by vaibhavchaubey** [Sulagna-Dutta-Roy/Webeginner-projects#9]
### Is your feature request related to a problem? Please describe.

Hello Ma'am,
I would like to work on the HTML, CSS, and Javascript-based Todo-List, which allows users to add their daily tasks. As there is always a need for a list in which we can write our tasks so that we can't forget them. That's why I want to work on this Todo-List project.

As soon as you assign me the issue, I can get to work.
Waiting for your response 😊

### Describe the solution you'd like.

The solution is pretty simple. I will add a user-friendly Ul that will helps the users to add their daily tasks easily. This list can help them prioritize various tasks so they know what ones to assign first.

### Describe alternatives you've considered.

I will try to add a more responsive and efficient UI.

**Comment by Sulagna-Dutta-Roy** [comment]
Wait until 1st August Inauguration then I will assign to you

**Comment by vaibhavchaubey** [comment]
Thanks for your reply

**Comment by iamrahul8** [comment]
Seems no further update from assignees
Assign it to me @Sulagna-Dutta-Roy
