### ISSUE TITLE
Title: Image Gallery 

### ISSUE THREAD

**Issue by Vanshiii203** [Sulagna-Dutta-Roy/Webeginner-projects#90]
### Is your proposal related to a problem? Please describe.

I would like to create an image gallery which will contain images and the description link of famous places, food ,festivals of India.

**Comment by Vanshiii203** [comment]
@Sulagna-Dutta-Roy I finished the work and am waiting for the previous PR to be merged so that I can create another PR for this.

**Comment by Sulagna-Dutta-Roy** [comment]
Yes you can make PR. create a new branch then make this PR.
